version: "3.9"

services:
  db:
    image: postgres:15   #this is the image from wich the container is creating
    container_name: postgres_db
    restart: always
    environment: #env values for when it creates the db in the docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:  #where in my docker it stores the data 
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: Backend
    restart: always  #if a problem it should always restart
    ports:  #machine port: docker port
      - "4000:4000"
    depends_on:
      - db
    environment:  #env variables 
      - dbhost=db

volumes:
  db_data: